### ISSUE TITLE
Image patch creation issues for RGBA images

### ISSUE THREAD

**Issue by beijbom** [beijbom/coralnet#275]
As the title suggests, the patch generation fails for RGBA images. 

The error triggers on this page: https://coralnet.ucsd.edu/label/3679/example_patches_ajax/?page=1

Here's the log for one of the RGBA errors: https://coralnet.ucsd.edu/admin/errorlogs/errorlog/2250/change/

If you expand the local vars under `generate_patch_if_doesnt_exist(point.pk)`, you should see the image and source in question.

**Comment by beijbom** [comment]
@StephenChan : what is our routine for text fixtures? In this case, it would be nice to store the problematic image itself somewhere and write a unit-test that makes sure it can be cropped without problems. But I don't see any such mechanisms in the repo. Do you have any thoughts on this? The very simplest way would be to create a `fixture` subfolder in the `test` folders, and simply commit the image to the repo. But there may be better ways.

**Comment by beijbom** [comment]
Ok. So I figured this one out. It has to do with the Pillow package upgrade. Refer to this thread:
https://github.com/python-pillow/Pillow/issues/2609

Copying the image locally, and using an older version of PIL I was able to crop and save fine. When I updated the reqs. to the current version I got the same error as in production. The fix is simple:
```
im = im.convert('RGB')
```
I will push a fix soon.

**Comment by StephenChan** [comment]
> what is our routine for text fixtures? In this case, it would be nice to store the problematic image itself somewhere and write a unit-test that makes sure it can be cropped without problems. But I don't see any such mechanisms in the repo. Do you have any thoughts on this? The very simplest way would be to create a `fixture` subfolder in the `test` folders, and simply commit the image to the repo. But there may be better ways.

We don't currently have a mechanism for this. Our image format tests are currently pretty limited, only consisting of images that are trivial to create programmatically, which is why we haven't needed such a thing yet. (See `upload/tests/test_images.py` - tests any .jpg, any .png, any .bmp, image of specific resolution, empty file.)

For this issue's purposes, I think we can also create the image programmatically during the test - seems like it just has to define RGBA data, nothing too fancy. Though I do like your idea in general. We might run into more subtle image decoding challenges later (especially if we get into something like EXIF support), and sometimes it's nice if you can manually inspect what's being tested. I'm OK with a `fixtures` subfolder in the `tests` folders, since I haven't heard of some other specific way to set this up. I'll leave it up to you on whether to add such a thing now or later.

Also, I should note that in this particular case (the error log at the top of this issue), the image is in a private source. So we can't copy that image into a publicly accessible repo. We should make a new image that does something similar (and make sure it also breaks the original code before you fixed it).

I'll comment on the PR sometime tomorrow.

**Comment by beijbom** [comment]
Thanks. Ok, seems we are on the same page. I used the image generation code this time around. Let's see if we need the stored fixtures later on.
