### ISSUE TITLE
API: Throttling system which accounts for complexity of deploy requests

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#277]
(Original issue title: "API: Quota system which gives requests different weights for throttling purposes")

I've tweaked the scope of issue #189 so that it includes basic rate limiting (e.g. throttle after x requests per hour), but does not distinguish the cost of different requests. This issue here will deal with the latter task.

Previously, I figured we could assign a weight to each different endpoint in the API (read metadata, create source, deploy, etc.) to account for the fact that, for example, any 'read' operation should be less expensive in terms of server resources than a 'deploy' operation. However, if we look at 'deploy' alone, this scheme wouldn't be nuanced enough. These characteristics could greatly influence the server resources required for a deploy:

1. Image count. A single deploy operation can request classification of 1 image, or multiple images, up to some upper limit that we define (for example, 100).
2. Point count per image. A deploy operation can include 1 point per image, or up to some upper limit that we define (for example, 1000 points per image).
3. Image resolution. A deploy can specify images that are 4 megapixels each, or 40 megapixels each.
4. Image filesize. A deploy can specify images that are 1 MB each, or 20 MB each.

So, I think it's crucial for us to weight different requests based on characteristics like these. For example, for deploy, we could say 1 MB of image filesize uses 5 quota units, and 1 point uses 1 quota unit. So if you call deploy on a 5 MB image with 20 points, that uses 5\*5 + 20\*1 = 45 quota units. And once you use 5000 quota units in one hour, you have to wait. Something like that.

Implementation-wise, this seems to go beyond django-rest-framework's basic rate limiting feature, since I think that feature can only count rates/quotas at the time an API endpoint is called. But for deploy, image resolution and filesize are evaluated when we download an image from the requested URL, and that download would happen in an asynchronous task. So, hopefully django-rest-framework provides some customization hook which lets us add to the quota at any time.

**Comment by StephenChan** [comment]
I've thought of a pretty simple idea which could account for most of the concerns above: Allow each user to have up to X active deploy requests at a time.

'Active' means the deploy jobs haven't completed yet; they're either pending or in progress. We could make X = 3, for example. Then if we keep the image limit per request at 100, that means the most efficient way to use the API would be to submit 300 images to begin with (3 deploy requests of 100 images each), check the job statuses periodically, and submit another 100 images each time a job finishes.

In general, this should make people wait longer when their requests take longer (larger images to download, larger images to process, more points, etc.), and when the spacer queue is more busy. So it seems to account for a lot of factors, without having to actually track all of that stuff in detail.

**Comment by beijbom** [comment]
I haven't given this much thought but this does sound reasonable. Simple is usually better. I do wonder if we are putting the horse before the cart, though? Until we have a lot of users, does it make sense to even have limits? Initially, we can just configure some alerts on AWS that pings us if usage goes up a lot, and then we can see what is going on. One  way could be to make a "hidden url" similar to `/backend_overview` that lists the number of deploy requests by user, completed, pending, etc. Just to give us a dashboard to monitor usage in these early days. @kriegman : what are your thoughts?

**Comment by StephenChan** [comment]
> I haven't given this much thought but this does sound reasonable. Simple is usually better. I do wonder if we are putting the horse before the cart, though? Until we have a lot of users, does it make sense to even have limits?

Yeah, I suppose it's not likely that we'll run into issues in the early stages. But unlimited deploy does seem fairly easy to abuse compared to 'traditional' image upload. Submitting a bunch of image URL strings is quite lightweight from the client side, while being potentially expensive on the server side (have to download all of those images, for a start). I guess that's my main concern. But if you think it's doable enough to catch any odd activity before it gets too expensive, then I'm fine with addressing this later.

> Initially, we can just configure some alerts on AWS that pings us if usage goes up a lot, and then we can see what is going on. One way could be to make a "hidden url" similar to `/backend_overview` that lists the number of deploy requests by user, completed, pending, etc. Just to give us a dashboard to monitor usage in these early days.

That does sound like something we'd probably want either way.

**Comment by beijbom** [comment]
> Yeah, I suppose it's not likely that we'll run into issues in the early stages. But unlimited deploy does seem fairly easy to abuse compared to 'traditional' image upload. Submitting a bunch of image URL strings is quite lightweight from the client side, while being potentially expensive on the server side (have to download all of those images, for a start). I guess that's my main concern.

That is a great point. I didn't think about that. A minor coding error on their end can end up spawning millions of deploy calls which we very costly on our end. And since we don't charge for the service, that is bad news. I suppose I'm in favor, then, of your suggestion.

... and great that we agree on the monitor. Can you create an issue to that effect?

**Comment by kriegman** [comment]
I haven't read the thread through, but I think we do need some controls on
the API. It could be very easy to consume a LOT of resources
fi it's free. e.g., it might be easier codingwise to just keep calling the
API rather than storing/caching results. Program errors as Oscar mentioned.
NOAA has plans for these mosaics, and they have thousands of images per
mosaic and hundreds of mosaics. Imagine if they start doing a
"Sweep" of say preprocessing algorithms etc.

I do think it's important to both have logs and guard rails, especially
once the API goes public.
There may be a need also to provide users with stats or a dashboard so they
know what's going on and if they're about to bump up against a limit.

David

**Comment by StephenChan** [comment]
> A minor coding error on their end can end up spawning millions of deploy calls which we very costly on our end. And since we don't charge for the service, that is bad news.

Exactly - even if we're not much of a target for intentional abuse, there can be loop-iteration bugs or something.

> and great that we agree on the monitor. Can you create an issue to that effect?

Will do. Relatedly, I'll also change the title of this issue since I'm not favoring a complex weighting system anymore, at least for now.

> There may be a need also to provide users with stats or a dashboard so they
know what's going on and if they're about to bump up against a limit.

That would be good to have, yeah. I'm actually not sure if user-facing usage stats/warnings are common in the big-name APIs out there, but if it's not that much effort then we should do it. I wonder if there's a standard for reporting usage stats as part of API responses; I'll look into that.

**Comment by kriegman** [comment]
Well, if we shut off service, then they'll want to know why. Perhaps they
just have to log in and go to their profile page?
I believe that all API calls have to be from a registered user.

David

**Comment by StephenChan** [comment]
To clarify, yeah, it is standard for APIs to respond with HTTP code 429 (too many requests) and an appropriate error message when the limit has been exceeded. Actually, the simple throttling we currently have in place already does that. I agree that part is important.

So the question after that is, how much additional rate-related info should we show to the user beyond that.

**Comment by StephenChan** [comment]
PR #296 implemented:

- Limiting concurrent deploy requests
- Letting the user know when they've reached the concurrent limit

So the scope of this particular issue should be taken care of. The user-facing status monitor is for issue #294.

**Comment by JordanMakesMaps** [comment]
Hi, I have a few questions about making requests with the new public API. I'm using the base of Steve Miller's code, but I'm working with Hong Kong MarineGeo images that are 6000 x 6000 pixels, and I'm hoping to get ~1% of those labeled so I can convert them into dense labels using another script I made.

But, because the images are large and I'm asking for a decent amount of labels, I wanted to get y'alls feedback on how this can be done in a timely manner, but without bogging down your server with requests or stealing precious server time from other patrons (I understand this is a free service you're providing and I don't want to abuse it as @StephenChan mentioned).

What exactly is the most efficient method with what you currently have setup? Should I ask for all of the annotations I need for for all the images I need in a single request (up to 100 images, of course), or should I only send one request at a time asking for all of the annotations for a single image? Alternatively, I could send a single request asking for some of the annotations I need for that image, and send additional requests for the rest of the annotations (e.g. batches of annotations for a single image)?

Also, how long should this take ? Currently I send a request and wait 60 seconds before asking for a status update... Should I be waiting much longer? I see that you implemented the limits of 1000 points per image, and 5 active requests. 

Anyways, any insight you can provide would be greatly appreciated, I love that you guys made this open and I'm really looking forward to seeing how CoralNet grows.

**Comment by beijbom** [comment]
hi Jordan,

thanks for your interest in the new API!

So 1% of a 6000x6000 image is 360k points, which is a lot. How many images
did you want to annotate that way? This will likely approach quite sizable
cloud-costs, so we may have to resl;ve that before you submit more jobs.

We are actually planning to roll-out a semantic segmentation end-point
which does full image segmentation directly in a much more efficient way,
but we don't have a fixed timeline yet. We are also rolling out a new and
improved computer vision backend (for point annotations) next month. This
new backend is both more accurate and faster, so if you can wait for that
to get rolled out, it'd be a win-win.

Re. the recent jobs you submitted and which are stuck: it appears to me the
compute nodes have run out of memory. We'd have to kill those manually and
then have you re-submit with fewer row/col locations. But let's first
figure out how many points and images in total you had planned to annotate.

cheers

**Comment by beijbom** [comment]
hey Jordan,

some comments inline below. How many images will you need to annotate?

On Tue, Oct 6, 2020 at 8:34 AM Jordan Pierce <notifications@github.com>
wrote:

> Hey Oscar, yeah I can definitely dial that back to .01% so each image
> would only get 3,600 labels; based on your knowledge of the system do you
> think this is doable without running into OOM errors or should I reduce
> even further? If not, I can wait for the updated backend to become
> available and try 'benchmarking' for you guys :)
>
3600 points per image is much more doable from a cost perspective. It would
cost approximately $0.05 to do 3600 points on one image -- the total cost
would depend on how many images you need. If it's less than, say, 1000
images we can absorb that cost.

Now, from a systems perspective we have a limit of 1000 points per image.
With the current system (soon to be deprecated) it seems you need to use
even fewer due to OOM problems.  So you'd need to make multiple calls per
image, each with perhaps 200 points or so. Then you can accumulate things
on your side once the jobs are complete.

Semantic segmentation, heck yes! Are you allowed/willing to disclose your
> approach to this task, whether it's using the existing sparse points
> somehow or if you're training an FCN?..
>
Yeah, it's a simple FCN. We still train on the point annotations, but then
make the network fully convolutional. It's pretty straight-forward. LMK if
you want to get involved. :)


> Also, I'm a bit new to making requests to servers, but it is somehow
> possible on y'alls end to embed a message in a status check indicating that
> there was an OOM error as a result of my initial request? And if so, I
> could from my end send a cancel request so you don't need to kill them
> manually and it alleviates the bottleneck?
>
Yeah, when we roll out the new backend we will be able to give better
feedback. For now, if a job isn't complete within 24 hours you can assume
it's broken. The best we can do at the moment is sending an email to this
thread so we can cancel it on our end. Sorry about that.

@Stephen Chan <stephenjchan@gmail.com> : correct me if I'm wrong but it
seems we don't have a way for folks to cancel jobs?

I see 5 requests in the queue right now, all of which seem to be stuck.
Should I go ahead and cancel those?

**Comment by JordanMakesMaps** [comment]
@beijbom sounds good. I actually won't be doing all 900 as of now, maybe just 5 as a proof on concept. Also yes, if they're still active they can be killed and I'll start again with smaller batches, thanks.

I definitely am interested in how you plan on implementing the semantic segmentation component, but, are you doing something like [Reus et al. 201](https://sci-hub.do/10.1109/oceanskobe.2018.8559302) or [Alsonso et al. 2019](https://sci-hub.do/10.1002/rob.21915)? Or are you literally taking the CNN that is currently trained on a source, converting it into some FCN-style architecture and then feeding it whole images? Or maybe with patches of the same size that it was originally trained on and then concatenating all of the output segmentation maps together? 

Also, if users can't cancel it on their end, what do you think about a time limit of 24hrs or so with no amount of progress triggering an automatic kill? Again, that way you guys don't need to play clean up.

**Comment by beijbom** [comment]
Ok, great. 900 images is no problem. Or indeed 5. haha. I was worried you'd
say 100k images. :)

Yeah, I just killed those old jobs, so go ahead and submit new ones.
Perhaps shoot for around 200 row/col locations per job and it should go
through fine.

We are just using the original FCN design [Long et al. 2015
<https://arxiv.org/abs/1411.4038>]. So we start with the base-CNN that is
shared across all sources, and then add the source-specific classiifer as a
1x1 conv layer, and then make the whole thing fully convolutional so that
we can feed in the whole image. Qimin, copied is working on if you want to
chat more.

cheers

**Comment by qiminchen** [comment]
@beijbom @JordanMakesMaps yes, the idea is pretty straightforward, I tried to implement the dense prediction in Pytorch and had some results but I'm still working on it and verifying if my code is working correctly. I will let you know once I have something available. Let me know if you want to chat more, we can open another issue to discuss that.

**Comment by JordanMakesMaps** [comment]
Hey @qiminchen that sounds awesome, looking forward to seeing it! Yeah actually if you could create a new issue for that, that'd be cool because I'd like to learn more and maybe try to mimic what y'all are doing but in Keras. I'd like to see if it's better/more efficient than what I'm currently doing.  

@beijbom sorry to keep spamming your inbox but I'm still getting a 429 response error; are they still showing up as active on your end?

**Comment by beijbom** [comment]
@JordanMakesMaps : gotya. No worries. @StephenChan : can you mark the jobs as cancelled on the DB side?

**Comment by StephenChan** [comment]
@beijbom Right - just canceled the jobs on the database side. @JordanMakesMaps : Should work now, go ahead and try again.

> Also, if users can't cancel it on their end, what do you think about a time limit of 24hrs or so with no amount of progress triggering an automatic kill? Again, that way you guys don't need to play clean up.

There can potentially be a queue if we get more API users later, so I'm not sure about a time limit, but I do think it makes sense to let users cancel.
