### ISSUE TITLE
Can't remove label from labelset if it still has unconfirmed annotations

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#289]
I tried out PR #285 (management command to replace annotations) in production, and it works, but it made me think of something else.

The management command only changes CONFIRMED annotations for a label. I did it this way because we probably want unconfirmed annotations to be synced with the Score and valresult structures, and the easiest way to make sure those things are all synced is to just train and accept a new classifier.

One problem, however: currently, the labelset 'Add/Remove Labels' page only lets you remove a label from the labelset if it has no annotations in the source whatsoever. This includes unconfirmed annotations. Also, the label might not have enough impact on overall classifier accuracy to allow a new classifier to get accepted. So there's no guarantee that the unconfirmed annotations would get changed anytime soon.

It seems we should modify the page to let users remove a label if it has no **confirmed** annotations - unconfirmed would be OK.

Once the user submits their change to the labelset, the backend data for the source will get reset, including erasing the unconfirmed annotations for that unwanted label... after an `apply_async()` call, that is. There may be a brief period where the source has unconfirmed annotations for a label that's not in the labelset. I'm not sure whether that could lead to any strange errors. If so, we could possibly delete the unconfirmed annotations for that label synchronously, as part of the labelset change request, instead of doing it asynchronously.

@beijbom Does this all make sense? Does anything else come to mind that we should watch out for here?

**Comment by beijbom** [comment]
Great points, thanks for bringing this up. Two comments. 
- Ideally it should be enough to switch all CONFIRMED AND UNCONFIRMED annotations for the source to the new label. But since there are some meta-data stored outside the DB schema (e.g https://github.com/beijbom/coralnet/issues/288, but also the internal representation of the classifier objects from scikit learn), we need to err on the side of wiping out all classifiers and starting over, just like we do with any label-set change. In other words, we need to call https://github.com/beijbom/coralnet/blob/master/project/vision_backend/tasks.py#L321 as part of that management command. This deletes all robot annotations for that source, so you will end up deleting all CONFIRMED annotations of the old label and ALL UNCONFIRMED annotations for the whole source. I'm sorry I didn't catch this during review.
- Regarding your comment on "It seems we should modify the page to let users remove a label if it has no confirmed annotations - unconfirmed would be OK.". Agreed, we can do that assuming we still trigger a full wipe off the vision backend for that source. At least until we have a way to retrofit the classifiers objets and val results data structures.

**Comment by StephenChan** [comment]
Okay, so we're agreed on this part - and yes, submitting this page's form does trigger a backend reset for the source:

> It seems we should modify the page to let users remove a label if it has no confirmed annotations - unconfirmed would be OK.

For the management command, it seems we have a few options on what it should do:

Option 1, leave as is:

- Change only the source's confirmed annotations of label A to label B.

Option 2:

- Change all of the source's annotations of label A to label B.
- Backend-reset the source.

Option 3:

- Change all of the source's annotations of label A to label B.
- Remove label A from the source's labelset.
- Backend-reset the source.

My thinking is that if we do Option 1 or Option 2, chances are high that the user's next move is to remove label A from the source's labelset, using the Add/Remove Labels page (which already triggers a backend reset). So I think Option 1 or Option 3 would make the most sense. The difference would be letting the user actually change the labelset, versus doing it for them. Thoughts?

**Comment by beijbom** [comment]
I’m not a fan of Option 1 since it leave the source in broken state. Tho
other 2 both work but I’m leaning towards option3 for a management command
since the user will want to remove label A anyways. And this way we don’t
reset the backend twice.

**Comment by StephenChan** [comment]
Sounds good, I think I'd favor option 3 as well. In the odd case that the source owner still wants label A in the labelset, they can always add it again afterwards.

**Comment by StephenChan** [comment]
Addressed in PR #290.
