### ISSUE TITLE
Calcification rate export: Support user-specified label rates

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#372]
Prerequisite: #369

When exporting calcification rates for a source, #369 should have given two options for specifying label calcification rates:

- Use the Indo-Pacific default rates
- Use the Atlantic default rates

And here we'll add a third option:

- Specify custom rates

When the third option is picked, a CSV-upload form field appears which lets you upload the rates as a CSV. The CSV format could match the table format shown in issue #368.

The text for each of the first two options (Indo-Pacific default, Atlantic default) should include a download link to a CSV of the default rates (for that source's labelset). So the recommended way to specify custom rates would be to download one of the default-rates CSV files first, then edit the CSV file locally to change the default rates to custom ones, then upload the edited CSV using the form field provided.

Then once you click Go on the export form, the calcification rate computations use the custom rates instead of default rates.

See #377 for saving custom rates tables (on a per-source basis) for subsequent exports.

**Comment by traviscourtney** [comment]
I think it would be really great for the custom rate table to have a unique identifier, perhaps the name of the uploaded .csv or some user-defined name so that the ID for that rate table could be included in the calcification export in #369 to increase traceability for where the calcification rate data came from.

If possible, I think the #377 implementation would be really nice such that users could upload their custom rate table .csv to an image source and have it saved directly to that source with a distinct name. I suspect this would improve traceability and consistency especially for larger collaborative CoralNet projects with multiple users.

**Comment by StephenChan** [comment]
Yes, I think for a start we can use the name of the uploaded .csv, and make it clear to the user that the filename will be used as the table ID for traceability. Then if #377 is implemented (I hope I get to it), we can make it a little nicer and have a text field to enter a name - that's a good point that #377 would be important for consistency between source collaborators.

**Comment by StephenChan** [comment]
Done in PR #404.
