### ISSUE TITLE
Update Pillow to 6 or later

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#394]
Not urgent currently, but would be nice to get out of the way. May not be super easy to do though. I gave this a quick try and got: `PermissionError: [WinError 32] The process cannot access the file because it is being used by another process` on a bunch of tests.

**Comment by beijbom** [comment]
Interesting. I know windows can be a bit fickle with these sorts of things.
Tests are running fine in CI: https://github.com/beijbom/coralnet/pull/398.

PIL is only imported in 5 places. Can you see if you can resolve the issues
on your local dev system? This page has some hints:
https://stackoverflow.com/questions/27215462/permissionerror-winerror-32-the-process-cannot-access-the-file-because-it-is

**Comment by StephenChan** [comment]
I'll look into it now.

**Comment by StephenChan** [comment]
Completed by PR #398.
