### ISSUE TITLE
Sources with only 1 label keep getting training errors

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#412]
Currently happening with source 1833.

`need_new_robot()` returns `True` for the source, since it has the minimum number of annotated images and it hasn't successfully trained a robot yet. However, spacer returns an error every time it tries to train, because the training data only has 1 unique label in it:

```
  File "/workspace/spacer/spacer/train_utils.py", line 58, in train
    raise ValueError('Not enough classes to do training (only 1)')
ValueError: Not enough classes to do training (only 1)
```

It turns out the source's labelset also only has 1 label, but in general, the annotations' contents are the determining factor here.

A few possible ideas:

1. Return from the `submit_classifier()` task if the training data only has 1 label in it. Pretty straightforward. However, since `need_new_robot()` will continue to return True for this source, we'll keep seeing the source highlighted in red in the Backend Overview page.

2. Change `need_new_robot()` to check if the training data only has 1 label in it, as the last check before returning True. I don't think the query is super simple/fast, since we have to check only the annotations in the confirmed images - not just all the confirmed annotations. So it could take on the order of 20+ seconds per small/medium source that needs a robot. This delay would happen each time we open Backend Overview, and during the daily `submit_all_classifiers()` loop (as opposed to during the `submit_classifier()` task).

3. Change spacer's training to handle the trivial case of 1 unique label, returning a valid classifier instead of giving an error.

4. Add another classifier status option, "Not enough labels". Update the `submit_classifier()` task to catch the case where the data only has 1 unique label. When this case is caught, set the classifier status to "Not enough labels", and return from the task without calling spacer. When the latest classifier's status is "Not enough labels", treat it like the "Rejected for low accuracy" case: submit a new classifier when we have 1.1x the number of confirmed images.

Option 3 is probably the simplest option from CoralNet's perspective, so I'd want to lean towards that, but I'm not sure how simple (or possible?) it is in spacer. If Option 3 is not particularly easy, then Option 4 might be the next best.

**Comment by StephenChan** [comment]
Updated option 2's ramifications:

> Change `need_new_robot()` to check if the training data only has 1 label in it, as the last check before returning True. I don't think the query is super simple/fast, since we have to check only the annotations in the confirmed images - not just all the confirmed annotations. So it could take on the order of 20+ seconds per small/medium source that needs a robot. This delay would happen each time we open Backend Overview, and during the daily `submit_all_classifiers()` loop (as opposed to during the `submit_classifier()` task).

**Comment by StephenChan** [comment]
Added an option 4 to the original post.

**Comment by beijbom** [comment]
One one level, it should be fine. If there is only 1 class during training, we should just predict that one class for all inputs. 

The problem is that we can't train a LogisticRegression model with 1 class. Scikit-learn will throw an error if we try. That means that we can't run the classification step as-is since we won't have a trained model. See e.g. https://github.com/beijbom/coralnet/blob/master/project/vision_backend/tasks.py#L239

One hack I can think of is to add a dummy label during the make_dataset step. Or rather, change one of the `gt_label` entries to another id in the source's label-set. If we only change one, the classifier should basically never return that label.
https://github.com/beijbom/coralnet/blob/1f47f666a783f5ed4bcb5057513a4ae76e3d2d8c/project/vision_backend/task_helpers.py#L132 

Unfortunately, it get's worse. The trainer requires 2 labels in both the train and reference split: https://github.com/beijbom/pyspacer/blob/master/spacer/train_utils.py#L54.

The reference set is created on-the-fly to calibrate some hyper parameters:
https://github.com/beijbom/pyspacer/blob/master/spacer/train_utils.py#L37

So, we'd need to add those dummy labels for multiple images, so this idea seems dead in the water.

A better solution would to have the trainer code special-case the single-label case and store e.g. a JSON file that contains the label_id. We'd then need to make load_classifier robust to this here: https://github.com/beijbom/pyspacer/blob/d3bdb89b37e469cdf9853d1a3378590485ae6507/spacer/storage.py#L216.

For example, catch errors in `pickle.loads` and instead load that JSON file, and instantiate a DummyPredictor object that supports the `predict_proba` call here: https://github.com/beijbom/pyspacer/blob/master/spacer/tasks.py#L104

Sorry -- no really good options here I'm afraid. :/

**Comment by StephenChan** [comment]
Thanks for the detailed breakdown. I guess I might go for the 'option 4' I listed, then, since recognizing a special-case 'fake' classifier doesn't seem particularly cleaner (or easier, for me).

**Comment by StephenChan** [comment]
PR #420 is now in production, so we'll see if that cleans up the rest of the regularly-occurring spacer errors.

**Comment by StephenChan** [comment]
Looks like it did. The two applicable sources at this point are 1833 and 2813, and both are detected as not needing a new robot.

(Of note, 2813 has exactly 1 annotation of a second label; but since that 1 annotation can't go into both the training and validation sets, the training labelset still ends up being size 1. Good to detect that case correctly.)
