### ISSUE TITLE
Question: Why does downloading annotations (Export Annotations, CSV) take so long?

### ISSUE THREAD

**Issue by Jordan-Pierce** [beijbom/coralnet#460]
Just curious. Does selecting the additional columns slow down the process?

Jordan

**Comment by StephenChan** [comment]
Hi Jordan,

This is something that just needs to be looked into more, but my best guess is that the Annotations in the database aren't being accessed in a very efficient way. And since there can easily be 10,000s of annotations in an export, that adds up. My impression is that it's very slow regardless of the options used - although the machine suggestions option likely makes it a good deal slower on top of that.

I'm planning to look into the export function with a tool like django-querycount when I get the chance.

(For my reference: see issue #13 )

**Comment by Jordan-Pierce** [comment]
@StephenChan thanks for the reply. Really appreciate the work y'all are doing!
