### ISSUE TITLE
Question: Editing / Deleting Privilege of Labelsets

### ISSUE THREAD

**Issue by Jordan-Pierce** [beijbom/coralnet#475]
Hi @StephenChan I'm back,

Thanks for the input on the API, I'm currently working on some tools that help automate the interaction with CoralNet for a project that will use CoralNet's API downstream.  I'm now approaching the point of labelsets, and I had a few questions for you:

- All labelsets are made public, and the approval process for submission seems to be mostly automated; since users can create private sources, were there ever thoughts on letting users create private labelsets? I know the objective of CoralNet is be altruistic, but I'm coming more from the perspective of not wanting to "litter" up the global labeset list with potential duplicates or very niche labels.

- Given that users have the ability to create a labelset, would it be possible in future to edit or delete a labelset (if no other sources have started using it)? if not delete, maybe editing the description, thumbnail, etc.? That being said, can you delete [7721](https://coralnet.ucsd.edu/label/7721/)? 😅 It was test.

Thanks

**Comment by StephenChan** [comment]
Hi Jordan,

> All labelsets are made public, and the approval process for submission seems to be mostly automated; since users can create private sources, were there ever thoughts on letting users create private labelsets? I know the objective of CoralNet is be altruistic, but I'm coming more from the perspective of not wanting to "litter" up the global labeset list with potential duplicates or very niche labels.

Although we're notified by email about each created label, they are indeed auto-approved and generally not contested unless they're really egregious (e.g. nothing to do with marine surveys).

The path we took with labels has certainly had tradeoffs, and I think it's fair to say that the global labelset is already cluttered! But getting everyone to draw from the same pool of labels has brought value to CoralNet. Classifiers may be source-specific, but the [feature extractor (network)](https://coralnet.ucsd.edu/blog/a-new-deep-learning-engine-for-coralnet/) is trained across different sources, and the only way that works is with labels shared between those sources.

The idea of private labels certainly has merits, and we've alluded to it in part of issue #165. It would certainly help some folks get started with CoralNet more rapidly. But the ratio of public to private sources is fairly low, including among the bigger sources, and there'd be a good chance that the same would happen with labels if we were to allow private labels. Maybe it'd still work out, but it's a significant philosophy change which would need clearer justification to definitely go on our roadmap.

In terms of managing the large size of the label pool, the 'verified' filter is there to help folks narrow things down a bit, and the 'duplicate' filter hopefully helps some as well, but it's certainly not a perfect situation still. Issue #160 is something that I'm looking forward to working on when we can, because the 'combinatoric' labels that specify growth forms and coral health (e.g. Leptoseris, Leptoseris Branching, Bleached Leptoseris) seems to be our biggest source of clutter/redundancy.

> Given that users have the ability to create a labelset, would it be possible in future to edit or delete a labelset (if no other sources have started using it)? if not delete, maybe editing the description, thumbnail, etc.?

That's partly already in place - if you are the admin of the only source(s) that use the label, then near the top of the label page, you should see a link to edit the label (but not delete it).

> That being said, can you delete [7721](https://coralnet.ucsd.edu/label/7721/)? 😅 It was test.

Sure! Done.

**Comment by Jordan-Pierce** [comment]
Hi @StephenChan, thanks for pointing out the ability to edit, I don't know how I missed that! Also, thanks for deleting that test labelset.

So our project has it's own labelset, and my first approach was just to identify existing CoralNet labelsets that closely match each of ours. I was using fuzzy logic to find the "best" match, and found that for about 65-70% of them, it works well. The others however are in a sense wrong, or do not exist. Question here:  if, for example, we have a rather ambiguous label called "black coral", and we end up using some existing labelset, such as "[ARMS-Black Coral](https://coralnet.ucsd.edu/label/5831/)" and these are technically not the "same", what are the ramifications to 1), our source classifier, and 2), the global feature extractor?

I'm getting the impression that choosing a labelset for a source is just as benign as choosing a name, nothing else. But I wanted to make sure that this was the case, and that if we chose a labelset that isn't technically the same, our classifier wouldn't suffer.

**Comment by StephenChan** [comment]
You may have not had the edit link available if you created the label but didn't actually add it to your source's labelset yet. I noticed the test label said it was used in 0 sources.

> Question here: if, for example, we have a rather ambiguous label called "black coral", and we end up using some existing labelset, such as "[ARMS-Black Coral](https://coralnet.ucsd.edu/label/5831/)" and these are technically not the "same", what are the ramifications to 1), our source classifier, and 2), the global feature extractor?

Hmm, good question - I want to say 1) no ramifications for your source classifier and 2) slight ramifications for the global feature extractor, but I'd have to check with @beijbom or @kriegman .

**Comment by kriegman** [comment]
1. Agree that there's no implication for your classifier
2, But it clutters meaning for the same label to have to different
meanings. e.g., the ARMS classes pertain to research that used ARMS plates,
and what grows on them vs. natural reefs. So, this would be a case for
creating a new label.

**Comment by Jordan-Pierce** [comment]
@StephenChan sorry, just a quick follow up. When editing a labelset, do users who created it have the ability to change the thumbnail, or is that  permanent?

Thanks

**Comment by StephenChan** [comment]
Yup, the label-edit page provides a field to change the thumbnail.
